# Generated by Django 5.0 on 2023-12-20 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="date",
            new_name="timestamp",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="writer",
        ),
    ]
